USE [master]

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'ParadigmiProject')
BEGIN
    CREATE DATABASE [ParadigmiProject];
END
GO

USE [ParadigmiProject];

GO
ALTER DATABASE [ParadigmiProject] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ParadigmiProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ParadigmiProject] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ParadigmiProject] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ParadigmiProject] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ParadigmiProject] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ParadigmiProject] SET ARITHABORT OFF 
GO
ALTER DATABASE [ParadigmiProject] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ParadigmiProject] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ParadigmiProject] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [ParadigmiProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ParadigmiProject] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ParadigmiProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ParadigmiProject] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ParadigmiProject] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ParadigmiProject] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ParadigmiProject] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ParadigmiProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ParadigmiProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ParadigmiProject] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ParadigmiProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ParadigmiProject] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ParadigmiProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ParadigmiProject] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ParadigmiProject] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ParadigmiProject] SET  MULTI_USER 
GO
ALTER DATABASE [ParadigmiProject] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [ParadigmiProject] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ParadigmiProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ParadigmiProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ParadigmiProject] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ParadigmiProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ParadigmiProject', N'ON'
GO
ALTER DATABASE [ParadigmiProject] SET QUERY_STORE = OFF
GO
USE [ParadigmiProject]
GO
/****** Object:  Table [dbo].[Courses]    Script Date: 03/05/2024 15:57:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Courses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Price] [decimal](18, 0) NOT NULL,
	[Type] [int] NOT NULL,
 CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderCourses]    Script Date: 03/05/2024 15:57:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderCourses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrdersId] [int] NOT NULL,
	[CoursesId] [int] NOT NULL,
 CONSTRAINT [PK_OrderCourses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 03/05/2024 15:57:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Street] [varchar](100) NOT NULL,
	[City] [varchar](100) NOT NULL,
	[ZipCode] [varchar](100) NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 03/05/2024 15:57:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Surname] [varchar](100) NOT NULL,
	[Email] [varchar](100) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[Role] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[OrderCourses]  WITH CHECK ADD  CONSTRAINT [FK_OrderCourses_Courses] FOREIGN KEY([CoursesId])
REFERENCES [dbo].[Courses] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderCourses] CHECK CONSTRAINT [FK_OrderCourses_Courses]
GO
ALTER TABLE [dbo].[OrderCourses]  WITH CHECK ADD  CONSTRAINT [FK_OrderCourses_Orders] FOREIGN KEY([OrdersId])
REFERENCES [dbo].[Orders] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderCourses] CHECK CONSTRAINT [FK_OrderCourses_Orders]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Users]
GO
USE [master]
GO
ALTER DATABASE [ParadigmiProject] SET  READ_WRITE 
GO
