services:
  web:
    image: api-dotnet-6
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
      - db-init
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MyDbContext=Server=db;Database=ParadigmiProject;User Id=sa;Password=SuperSecretPassword1235!!!!;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecretPassword1235!!!!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      - db
    environment:
      SA_PASSWORD: "SuperSecretPassword1235!!!!"

volumes:
  sqlserver-data:
